### ISSUE TITLE
our issue

### ISSUE THREAD

**Issue by DimkaKoval** [DanaTokarchuk/FanClub_of_Sleeping#4]
To do a project

**Comment by DanaTokarchuk** [comment]
We already have it

**Comment by DimkaKoval** [comment]
Add a history of university
[Новий Документ Microsoft Word.docx](https://github.com/DanaTokarchuk/FanClub_of_Sleeping/files/1931515/Microsoft.Word.docx)

**Comment by LiliyaTelehii** [comment]
В тих віршиках занадто часто вживається слово "гуцул". Мене це турбує.

**Comment by DimkaKoval** [comment]
Це не повинно тебе турбувати тільки через те що ти з Карпат
