### ISSUE TITLE
Ecolover

### ISSUE THREAD

**Issue by LiliyaTelehii** [DanaTokarchuk/FanClub_of_Sleeping#6]
Для запобігання збільшенню озоногового шару 1987 р. у Монреалі було підписано міжнародну Угоду про зменшення та подальшу відмову від виробництва речовин, які руйнують озоновий шар. Монреальський протокол про речовини, що виснажують озоновий шар, - це міжнародний договір, створений для захисту озонового шару шляхом припинення або обмеження виробництва певних речовин, що вважалися причинами виснаження озону. Монреальський протокол є незмінним супутником Віденської конвенції про охорону озонового шару. Норми цього документа мають більш конкретний, уточнювальний характер, аніж норми Віденської конвенції. У ньому міститься ПЕРЕЛІК РЕЧОВИН І ПРОДУКТІВ, ЯКІ РУЙНУЮТЬ ОЗОНОВИЙ ШАР. До них належать кондиціонери у легкових і вантажних автомобілях, холодильники, морозильні камери, льодогенератори, аерозольні продукти, фторполімери тощо.

**Comment by DimkaKoval** [comment]
це круто!
