### ISSUE TITLE
with file

### ISSUE THREAD

**Issue by DimkaKoval** [DanaTokarchuk/FanClub_of_Sleeping#8]
[Новий Документ Microsoft Word.docx](https://github.com/DanaTokarchuk/FanClub_of_Sleeping/files/1931555/Microsoft.Word.docx)

**Comment by LiliyaTelehii** [comment]
Пропоную до project "Волинь" добавити народну поему:
Вікна сині, двері сині.
Де ми діти?
На Волині,

**Comment by DanaTokarchuk** [comment]
ОК, додавайте

**Comment by DimkaKoval** [comment]
Не порти мій проект!)

**Comment by LiliyaTelehii** [comment]
А як Вам поезія невідомого автора;
Морда в сажі
Срака в глині
Зразу видно, що з Волині.
